In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import manify

In [3]:
# Can we run Gaussian mixture with a component manifold?
# If not, what's stopping us?

pm = manify.manifolds.ProductManifold(signature=[(-1, 2), (1, 2)])
cm = pm.P[0]

pm

In [25]:
pm.gaussian_mixture()

(tensor([[ 3.0832e+00, -6.4681e-01,  2.8439e+00, -4.8090e-01,  8.0262e-01,
           3.5289e-01],
         [ 1.4544e+01,  1.0654e+01,  9.8496e+00, -5.3318e-01,  8.4320e-01,
           6.8712e-02],
         [ 2.9099e+03,  2.0459e+03,  2.0692e+03, -3.7858e-01,  4.8153e-01,
           7.9045e-01],
         ...,
         [ 2.3363e+03,  8.3966e+01,  2.3348e+03, -3.4047e-01,  2.2919e-01,
           9.1190e-01],
         [ 1.9187e+02,  1.3452e+02,  1.3680e+02, -8.3083e-02, -4.0942e-01,
           9.0856e-01],
         [ 1.2878e+01,  8.1187e+00,  9.9458e+00,  2.9159e-01, -4.2810e-01,
           8.5540e-01]]),
 tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 

In [12]:
import torch
torch.arange(3).shape

torch.Size([3])

In [22]:
torch.cat([torch.arange(3), torch.randint(0, 1, (0,))])

tensor([0, 1, 2])